name: Build and upload bottles

on:
  pull_request:
    paths:
      - 'Formula/*.rb'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: homebrew/brew
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1
      - name: Update Homebrew
        run: brew update-reset $(brew --repository)
      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repository $GITHUB_REPOSITORY))
          ln -s $PWD $(brew --repository $GITHUB_REPOSITORY)
      - name: Build bottles
        env:
          HOMEBREW_BINTRAY_URL: https://dl.bintray.com/dawidd6/bottles-tap
          # workaround for error: invalid cross-device link
          HOMEBREW_CACHE: /home/linuxbrew/.cache
          HOMEBREW_TEMP: /home/linuxbrew/.tmp
        run: |
          mkdir /tmp/bottles
          cd /tmp/bottles
          brew test-bot --root-url=$HOMEBREW_BINTRAY_URL
          mv /tmp/bottles $GITHUB_WORKSPACE
      - name: Cache bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles-linux
          path: bottles
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1
      - name: Update Homebrew
        run: brew update-reset $(brew --repository)
      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repository $GITHUB_REPOSITORY))
          ln -s $PWD $(brew --repository $GITHUB_REPOSITORY)
      - name: Build bottles
        env:
          HOMEBREW_BINTRAY_URL: https://dl.bintray.com/dawidd6/bottles-tap
        run: |
          mkdir /tmp/bottles
          cd /tmp/bottles
          brew test-bot --root-url=$HOMEBREW_BINTRAY_URL
          mv /tmp/bottles $GITHUB_WORKSPACE
      - name: Cache bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles-macos
          path: bottles
  upload:
    runs-on: macos-latest
    needs:
      - build-linux
      - build-macos
    steps:
      - name: Get bottles-linux
        uses: actions/download-artifact@v1
        with:
          name: bottles-linux
          path: ./
      - name: Get bottles-macos
        uses: actions/download-artifact@v1
        with:
          name: bottles-macos
          path: ./
      - name: Create package
        env:
          HOMEBREW_BINTRAY_REPO: bottles-tap
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        run: |
          for package in $(ls -1 *.bottle.* | awk -F '--' '{print $1}' | uniq | tr '@' ':'); do
            curl \
              --user $HOMEBREW_BINTRAY_USER:$HOMEBREW_BINTRAY_KEY \
              --header "Content-Type: application/json" \
              --data " \
                {\"name\": \"$package\", \
                \"vcs_url\": \"$GITHUB_REPOSITORY\", \
                \"licenses\": [\"MIT\"], \
                \"public_download_numbers\": true, \
                \"public_stats\": true \
                }" \
              https://api.bintray.com/packages/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO || true
          done
      - name: Upload bottles
        env:
          HOMEBREW_BOTTLE_DOMAIN: https://dl.bintray.com/dawidd6
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        run: |
          brew update-reset
          brew test-bot --bintray-org=$HOMEBREW_BINTRAY_USER --ci-upload
      - name: Push branch
        env:
          GITHUB_USER: dawidd6
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: pr-${{github.event.pull_request.number}}
        run: git -C $(brew --repository $GITHUB_REPOSITORY) push -f https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git HEAD:$BRANCH
