name: Build and upload bottles

on: pull_request

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: linuxbrew/brew
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1
      - name: Setup tap
        run: |
          mkdir -p "$(brew --prefix)/Homebrew/Library/Taps/dawidd6"
          ln -s "$PWD" "$(brew --prefix)/Homebrew/Library/Taps/$GITHUB_REPOSITORY"
      - name: Build bottles
        env:
          # Seems like Github is mounting some volumes in home and workdir place.
          # Setting these help avoiding "Invalid cross-device link" errors.
          HOMEBREW_CACHE: /home/linuxbrew/.cache
          HOMEBREW_TEMP: /home/linuxbrew/.tmp
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
        run: |
          mkdir /bottles
          cd /bottles
          GITHUB_ACTIONS=true brew test-bot --root-url=https://dl.bintray.com/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO
          if ls *.bottle.*; then
            mkdir $GITHUB_WORKSPACE/bottles
            mv *.bottle.* $GITHUB_WORKSPACE/bottles
          fi || true
      - name: Cache bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles-linux
          path: bottles
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1
      - name: Setup tap
        run: |
          mkdir -p "$(brew --prefix)/Homebrew/Library/Taps/dawidd6"
          ln -s "$PWD" "$(brew --prefix)/Homebrew/Library/Taps/$GITHUB_REPOSITORY"
      - name: Build bottles
        env:
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
        run: |
          mkdir bottles
          cd bottles
          brew test-bot --root-url=https://dl.bintray.com/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO
      - name: Cache bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles-macos
          path: bottles
  upload:
    runs-on: macos-latest
    needs:
      - build-linux
      - build-macos
    steps:
      - name: Get bottles-linux
        uses: actions/download-artifact@v1
        with:
          name: bottles-linux
          path: ./
      - name: Get bottles-macos
        uses: actions/download-artifact@v1
        with:
          name: bottles-macos
          path: ./
      - name: Check bottles
        id: check
        run: |
          if ls *.bottle.*; then
            exist=true
          else
            exist=false
          fi || true
          echo "::set-output name=exist::$exist"
      - name: Upload bottles
        if: steps.check.outputs.exist
        env:
          HOMEBREW_BOTTLE_DOMAIN: https://dl.bintray.com/dawidd6
          HOMEBREW_BINTRAY_USER: dawidd6
          HOMEBREW_BINTRAY_REPO: bottles-tap
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          # Create packages on bintray if they don't exist.
          for package in $(ls -1 *.bottle.* | awk -F '--' '{print $1}' | uniq); do
            curl \
              --user $HOMEBREW_BINTRAY_USER:$HOMEBREW_BINTRAY_KEY \
              --header "Content-Type: application/json" \
              --data " \
                {\"name\": \"$package\", \
                \"vcs_url\": \"$GITHUB_REPOSITORY\", \
                \"licenses\": [\"MIT\"], \
                \"public_download_numbers\": true, \
                \"public_stats\": true \
                }" \
              https://api.bintray.com/packages/$HOMEBREW_BINTRAY_USER/$HOMEBREW_BINTRAY_REPO || true
          done
          # Upload bottles from current directory.
          brew update
          brew test-bot --bintray-org=$HOMEBREW_BINTRAY_USER --ci-upload
          # Push changes.
          git \
            -C "$(brew --repository $GITHUB_REPOSITORY)" \
            push \
            --force \
            https://$HOMEBREW_BINTRAY_USER:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git \
            HEAD:pr-${{github.event.pull_request.number}}
