name: Building and Uploading

on:
  workflow_dispatch:
    inputs:
      os:
        description: OS type
        required: true
      formula:
        description: Formula name
        required: true

jobs:
  build:
    runs-on: ${{github.event.inputs.os}}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Build bottles
        run: |
          brew test-bot --only-cleanup-before
          brew test-bot --only-formulae --skip-recursive-dependents --keep-old ${{github.event.inputs.formula}}
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: '*.bottle.*'
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Set up git
        uses: Homebrew/actions/git-user-config@master
      - name: Download bottles
        uses: actions/download-artifact@v2
        with:
          name: bottles
      - name: Publish bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
        run: brew pr-upload --debug --keep-old
      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
